name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Deploy Docker containers over SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.INSTANCE_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.KEY_PAIR_NAME }}
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-nginx-site:latest
            sudo docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-nginx-site:latest
            # і тут додати другий контейнер

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_key_pair_name: ${{ secrets.KEY_PAIR_NAME }}
      TF_VAR_public_key: ${{ secrets.PUBLIC_KEY }}
      TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
      TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}





